### ISSUE TITLE
Twingate 2023.250.8341 error exit code 1603

### ISSUE THREAD

**Issue by esplor** [Twingate-Labs/chocolatey-packages#1]
Hi, not sure if this is the right place to report this issue.

Twingate failed installation because of missing dependencies.
After running `choco install dotnet-6.0-desktopruntime` it installed without error codes.

Could desktopruntime be added as a dependency?

OSMajor = 10 OSBuild = 19045

**Comment by chenbishop** [comment]
@esplor Thank you for raising this, we are looking into this and aim to include this change in the next client release.

**Comment by chenbishop** [comment]
@esplor this issue should be resolved now. Closing the issue
